package com.example.api

import android.util.Log
import com.example.BuildConfig
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.concurrent.TimeUnit

object GeminiClient {
    private const val TAG = "GeminiClient"
    private const val MODEL_NAME = "gemini-3.5-flash"
    private const val BASE_URL = "https://generativelanguage.googleapis.com/v1beta/models/$MODEL_NAME:generateContent"

    private val client = OkHttpClient.Builder()
        .connectTimeout(45, TimeUnit.SECONDS)
        .readTimeout(45, TimeUnit.SECONDS)
        .writeTimeout(45, TimeUnit.SECONDS)
        .build()

    /**
     * Call the Gemini API. Anonymizes the prompt to be clean of sensitive details.
     */
    suspend fun generateContent(systemInstruction: String, prompt: String): String = withContext(Dispatchers.IO) {
        val apiKey = BuildConfig.GEMINI_API_KEY
        if (apiKey.isEmpty() || apiKey == "MY_GEMINI_API_KEY") {
            Log.e(TAG, "Gemini API Key is placeholder or missing!")
            return@withContext "Error: Please check AI Studio Secrets setup. No valid API Key was provided."
        }

        try {
            // Build Gemini Request JSON manually using Android's native JSONObject to avoid converter mismatches
            val root = JSONObject()
            
            // Contents
            val contentsArray = JSONArray()
            val contentObj = JSONObject()
            val partsArray = JSONArray()
            val partTextObj = JSONObject().put("text", prompt)
            partsArray.put(partTextObj)
            contentObj.put("parts", partsArray)
            contentsArray.put(contentObj)
            root.put("contents", contentsArray)

            // System Instruction
            if (systemInstruction.isNotEmpty()) {
                val systemInstructionObj = JSONObject()
                val systemPartsArray = JSONArray()
                val systemPartTextObj = JSONObject().put("text", systemInstruction)
                systemPartsArray.put(systemPartTextObj)
                systemInstructionObj.put("parts", systemPartsArray)
                root.put("systemInstruction", systemInstructionObj)
            }

            // Generation Config
            val generationConfig = JSONObject().apply {
                put("temperature", 0.4) // Slightly lower temp for stable, helpful advice
            }
            root.put("generationConfig", generationConfig)

            val jsonBody = root.toString()
            val mediaType = "application/json; charset=utf-8".toMediaType()
            val requestBody = jsonBody.toRequestBody(mediaType)

            val requestUrl = "$BASE_URL?key=$apiKey"
            val request = Request.Builder()
                .url(requestUrl)
                .post(requestBody)
                .build()

            client.newCall(request).execute().use { response ->
                if (!response.isSuccessful) {
                    val errBody = response.body?.string() ?: ""
                    Log.e(TAG, "API call failed with code: ${response.code}, body: $errBody")
                    return@withContext "Error analyzing data: API error code ${response.code}."
                }

                val responseBodyStr = response.body?.string() ?: ""
                val responseJson = JSONObject(responseBodyStr)
                
                // Parse: candidates[0].content.parts[0].text
                val candidates = responseJson.optJSONArray("candidates")
                if (candidates != null && candidates.length() > 0) {
                    val firstCandidate = candidates.getJSONObject(0)
                    val content = firstCandidate.optJSONObject("content")
                    if (content != null) {
                        val parts = content.optJSONArray("parts")
                        if (parts != null && parts.length() > 0) {
                            return@withContext parts.getJSONObject(0).optString("text")
                        }
                    }
                }
                return@withContext "No response was generated by the assistant. Please try rephrasing."
            }
        } catch (e: Exception) {
            Log.e(TAG, "Exception during analysis API: ", e)
            return@withContext "Error: Unable to connect to the assistant right now. (${e.message})"
        }
    }

    /**
     * Secure Baby Crying analysis helper
     */
    suspend fun analyzeCrying(description: String, suspectedReason: String, severity: String): String {
        val prompt = """
            Analyze this infant crying episode details:
            Description or symptoms: '$description'
            Parent suspected reason: '$suspectedReason'
            Parent marked severity: '$severity'
            
            Format response with:
            ### Possible Cause
            (Provide reassurance and a gentle explanation)
            
            ### Quick Actions (What to do)
            (Give exactly 4 clear bulleted items containing calming tips for the parent to try right now)
            
            ### Red Flags to Monitor
            (Alert of medical warning signs where they should stop trying to soothe and contact their pediatrician immediately)
        """.trimIndent()

        val systemInstruction = """
            You are an expert pediatric nurse and baby sleep consultant. 
            You provide supportive, calming, and medically cautious advice to highly stressed new parents.
            Never replace direct medical care, and emphasize safety check marks. 
            Do not use infant names or reveal personal information to remain compliant with privacy and high sensitivity guidelines.
        """.trimIndent()

        return generateContent(systemInstruction, prompt)
    }

    /**
     * Balanced Infant Meal Planner helper
     */
    suspend fun generateMealPlan(ageMonths: Int, preference: String, allergies: String): String {
        val prompt = """
            Generate an ideal baby meal planning guide for a baby of:
            Age: $ageMonths months old
            Feeding approach preference: $preference (e.g. Purées, Baby-Led Weaning, Mixed feeding)
            Allergies / foods to avoid: $allergies
            
            Format response with:
            ### Nutrient Focus
            (Short paragraph describing age-appropriate focus, e.g. Iron absorption, texture exposure)
            
            ### Daily Schedule Route
            (A realistic timeline showing bottle/breastfeeds, side snack, and solid food feedings)
            
            ### Prep and Safety Guidelines
            (Guidelines on baby portion sizes and safety procedures like testing for choke risk, perfect liquid consistency)
            
            ### 2 Simple Prep Recipes
            (Fast and easy baby meal instructions for stressed, sleep-deprived parents)
        """.trimIndent()

        val systemInstruction = """
            You are an outstanding pediatric dietitian skilled in weaning infants. 
            You deliver practical, scientifically supported solid-feeding ideas while emphasizing milk as the primary caloric source below twelve months. 
            Keep language plain, supportive, and accessible. Suggest foods rich in iron, healthy fats, and proper texturing.
        """.trimIndent()

        return generateContent(systemInstruction, prompt)
    }

    /**
     * Secure Postpartum and Parent Meal Planner helper
     */
    suspend fun generateParentMealPlan(stage: String, restrictions: String, allergies: String, preferences: String): String {
        val prompt = """
            Generate an ideal postpartum nutrient-dense meal planning guide for a new parent seeking:
            Postpartum Phase & Goal: $stage
            Dietary Restrictions: $restrictions
            Allergies / Foods to Avoid: $allergies
            Meal Prep Preferences: $preferences
            
            Format response with:
            ### 🌟 Nutrient Spotlight
            (Explain what postpartum nutritional needs are critical for this stage, e.g., tissue healing, milk supply boost, or maternal rehydration)
            
            ### 📅 Sample Recovery Menu
            (A suggested menu covering Breakfast, Maternal Lunch, Afternoon Recovery Snack, and Mineral-rich Dinner)
            
            ### 🍲 2 Quick postpartum healing Recipes
            (Provide two simple, comforting recipes that are easy to prep, nutritious, and support lactation or physical healing)
            
            ### 💡 Restoration & Self-Care tips
            (Quick actionable maternal suggestions highlighting hydration, easy digestion, and sleep optimization)
        """.trimIndent()

        val systemInstruction = """
            You are an expert postpartum nutritionist, maternal dietitian, and lactation consultant. 
            You address parent fatigue, hydration, and nutritional density to support childbirth recovery and breastfeeding. 
            Keep instructions exceptionally comforting, kind, practical, and fast to execute.
        """.trimIndent()

        return generateContent(systemInstruction, prompt)
    }
}
